### ISSUE TITLE
question about eval

### ISSUE THREAD

**Issue by gazelxu** [chunbolang/BAM#25]
when batch_size_val sets more than 1, bugs will occur like following:
Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/mnt/cache/xuguozheng/.conda/envs/torch1.8/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/mnt/cache/xuguozheng/.conda/envs/torch1.8/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/mnt/cache/xuguozheng/.conda/envs/torch1.8/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/mnt/cache/xuguozheng/.conda/envs/torch1.8/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 83, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/mnt/cache/xuguozheng/.conda/envs/torch1.8/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 63, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/mnt/cache/xuguozheng/.conda/envs/torch1.8/lib/python3.6/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [366, 500] at entry 0 and [333, 500] at entry 1

Dose the batch_size_val have to be 1(Every thing goes well when set to 1)? Or Is there anything else I shound pay attention to?

**Comment by chunbolang** [comment]
The current version only supports `batch_size_val=1`, because the resolution of each test image varies, namely setting [args.ori_resize=True](https://github.com/chunbolang/BAM/blob/main/test.py#L239).

**Comment by chunbolang** [comment]
Feel free to reopen this issue if there is any other confusion.
