### ISSUE TITLE
关于您给的pascal-5i base annotation数据集的问题

### ISSUE THREAD

**Issue by cs-xiyan** [chunbolang/BAM#63]
pascal-5i是从20个类别挑选五个作为查询集，剩下15个作为支持集，不同I代表不同采样方法，可是您给的base annotation，i无论是0还是3，无论是train还是val都只是1-15类。这是为什么呢？
![image](https://github.com/chunbolang/BAM/assets/42777375/998eb036-e382-4ec2-808c-c5770ed58398)
![image](https://github.com/chunbolang/BAM/assets/42777375/6b32299c-3088-4658-ae3e-4a12182f8b36)
![image](https://github.com/chunbolang/BAM/assets/42777375/221134e3-7a9f-4764-aa18-09e0dff94d25)

**Comment by cs-xiyan** [comment]
我好像理解怎么回事了，BAM 中的base_annotation实际上只是产生了支持集，被用于pspnet的训练，也就是支持分支，他是两段式训练。虽然都是1-15但是实际上包含了不同类别。不知道这样解释是否正确。

**Comment by qjmltz** [comment]
您好，我刚开始研究FSS，请问您知道为什么在BAM之前的模型，像是PFEnet和HSNenet、SSP都没有用到base_annotation，而为什么BAM用到base_annotation？HSNenet和SSP虽然有下载VOC2012的annotation，但似乎不加也没有关系。
非常期待您的回复，十分感谢！

**Comment by cs-xiyan** [comment]
我是这么理解的假设一共20类，base_annotation是将数据集进行了处理，选择15个类重新映射为1-15，比如前5类是novel class，后15类是base class，那么把6-20映射成1-15。然后新建一个数据集。其他模型并没有重新映射这步。因为需要用基学习器也就是传统语义分割模型先把15类分好。所以需要重新映射，方便后续损失计算。
[BAM](https://github.com/chunbolang/BAM/tree/main)/[util](https://github.com/chunbolang/BAM/tree/main/util)
/get_mulway_base_data.py 69-74 line

```python
for cls in range(1,num_classes+1):
        select_pix = np.where(label_tmp == cls)
        if cls in sub_list:
            label[select_pix[0],select_pix[1]] = sub_list.index(cls) + 1
        else:
            label[select_pix[0],select_pix[1]] = 0
```
BAM是两段训练，先训练好基学习器，分出15类，然后加载基学习器权重，再训练元学习器。
PFENET不需要这样，他是直接像传统语义分割一样读取image,和mask，在自定义dataset类部分直接分成支持集和查询集，直接训练。

**Comment by qjmltz** [comment]
> 我是这么理解的假设一共20类，base_annotation是将数据集进行了处理，选择15个类重新映射为1-15，比如前5类是novel class，后15类是base class，那么把6-20映射成1-15。然后新建一个数据集。其他模型并没有重新映射这步。因为需要用基学习器也就是传统语义分割模型先把15类分好。所以需要重新映射，方便后续损失计算。 [BAM](https://github.com/chunbolang/BAM/tree/main)/[util](https://github.com/chunbolang/BAM/tree/main/util) /get_mulway_base_data.py 69-74 线
> 
> ```python
> for cls in range(1,num_classes+1):
>         select_pix = np.where(label_tmp == cls)
>         if cls in sub_list:
>             label[select_pix[0],select_pix[1]] = sub_list.index(cls) + 1
>         else:
>             label[select_pix[0],select_pix[1]] = 0
> ```
> 
> BAM是两段训练，先训练好基学习器，分出15类，然后加载基学习器权重，再训练元学习器。 PFENET不需要这样，他是直接像传统语义分割一样读取image，和mask，在自定义数据集类部分直接分成支持集和查询集，直接训练。

非常感谢您的回复，让我对BAM的论文理解更加深了一层，对于初学者的我来说帮助很大，感谢~

**Comment by Bruce-W12138** [comment]
您好，我好像遇到了一个问题：在加载20类里面会出现不属于sub的20个类的情况：
Traceback (most recent call last):
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 634, in __next__
    data = self._next_data()
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data
    return self._process_data(data)
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data
    data.reraise()
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\_utils.py", line 644, in reraise
    raise exception
AssertionError: Caught AssertionError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\utils\data\_utils\worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\12264\.conda\envs\denseseg\lib\site-packages\torch\utils\data\_utils\fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "D:\WorkProject\SegTask\BAM-main\util\dataset.py", line 234, in __getitem__
    assert len(label_class) > 0
AssertionError

**Comment by liuqi018** [comment]
> 您好，我好像遇到了一个问题：在加载20类里面会出现不属于sub的20个类的情况： Traceback (most recent call last): File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 634, in **next** data = self._next_data() File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data return self._process_data(data) File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data data.reraise() File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch_utils.py", line 644, in reraise raise exception AssertionError: Caught AssertionError in DataLoader worker process 0. Original Traceback (most recent call last): File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\WorkProject\SegTask\BAM-main\util\dataset.py", line 234, in **getitem** assert len(label_class) > 0 AssertionError

**Comment by bowen099** [comment]
> 您好，我好像遇到了一个问题：在加载20类里面会出现不属于sub的20个类的情况： Traceback (most recent call last): File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 634, in **next** data = self._next_data() File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 1346, in _next_data return self._process_data(data) File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data\dataloader.py", line 1372, in _process_data data.reraise() File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch_utils.py", line 644, in reraise raise exception AssertionError: Caught AssertionError in DataLoader worker process 0. Original Traceback (most recent call last): File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data_utils\worker.py", line 308, in _worker_loop data = fetcher.fetch(index) File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "C:\Users\12264.conda\envs\denseseg\lib\site-packages\torch\utils\data_utils\fetch.py", line 51, in data = [self.dataset[idx] for idx in possibly_batched_index] File "D:\WorkProject\SegTask\BAM-main\util\dataset.py", line 234, in **getitem** assert len(label_class) > 0 AssertionError

请问您最后运用pascal复现出结果了吗？
